[project]
name = "lora-finetune"
version = "0.1.0"
description = "LoRA fine-tuning CLI tool"
authors = [
    { name = "Jonathan Salem", email = "jonathansalem5@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.8"
[project.scripts]
lora-finetuner = "lora_finetune.cli:entry"
